version: 2.1
orbs:
  docker: circleci/docker@0.5.0
workflows:
  build-and-push:
    jobs:
      - docker/publish:
          tag: latest
          extra_build_args: "--build-arg WAIFU_TIERLIST_DATABASE_URL=$WAIFU_DATABASE_TIERLIST_URL"
          image: xetera/waifu-tierlist
